### PR TITLE
Support backup v1

### LINKED ISSUE #4: Backups.proto updated by Signal-Android
The file `Backups.proto` has been updated in the Signal-Android repository in the following commit: https://github.com/signalapp/Signal-Android/commit/c6473ca9e63236af3eae9959a50cfa643d53272e

Here are the differences to the current version used by `signal_for_android_decryption`:

```
diff --git a/Backups.proto b/Backups.proto
index 98e4bdf..83227de 100644
--- a/Backups.proto
+++ b/Backups.proto
@@ -8,8 +8,7 @@ syntax = "proto2";
 
 package signal;
 
-option java_package         = "org.thoughtcrime.securesms.backup";
-option java_outer_classname = "BackupProtos";
+option java_package = "org.thoughtcrime.securesms.backup.proto";
 
 message SqlStatement {
     message SqlParameter {
@@ -55,8 +54,9 @@ message DatabaseVersion {
 }
 
 message Header {
-    optional bytes iv   = 1;
-    optional bytes salt = 2;
+    optional bytes  iv      = 1;
+    optional bytes  salt    = 2;
+    optional uint32 version = 3;
 }
 
 message KeyValue {
@@ -79,4 +79,4 @@ message BackupFrame {
     optional Avatar           avatar     = 7;
     optional Sticker          sticker    = 8;
     optional KeyValue         keyValue   = 9;
-}
+}
\ No newline at end of file
```

I'm not 100% sure that this means that any changes are needed in `signal_for_android_decryption`, but I though it might still be useful if I report it anyways.

For `signal-backup-decode` there is a PR addressing this changes, maybe this can give some pointers on what needs to be adapted: https://github.com/pajowu/signal-backup-decode/pull/60

### PR DESCRIPTION
**Pull request by lapseofreason**
Add support for the new Signal-Android backup version 1.

Commit from Signal-Android: https://github.com/signalapp/Signal-Android/commit/c6473ca9e63236af3eae9959a50cfa643d53272e

I tested it on the new backup format and it worked. Unfortunately, I don't have any old backups to test it on. So while I tried to preserve that functionality, I was not able to test it on old backup versions.

Fixes https://github.com/mossblaser/signal_for_android_decryption/issues/4

### CODE REVIEW

**Comment by frans-fuerst** [comment]
I just tried it on backup files from `2019-07-24-22-25-22`, `2021-08-27` and `2023-10-29-02-55-00` and it all worked for me! (didn't check the file contents, but the extraction completed without errors or warnings.

**Comment by lapseofreason** [comment]
@frans-fuerst Thanks for testing the PR!

**Comment by mossblaser** [comment]
Hello all, thanks so much for diagnosing, fixing and testing this! I'm sorry I'm a bit snowed under but will get this merged as soon as I can!

**Comment by lapseofreason** [comment]
Great, thanks a lot @mossblaser.

Btw, I quite enjoyed reading your writeup on the Signal-Android backup format, thanks for that.

**Comment by mossblaser** [comment]
Finally had chance to run through this and merge.

Once again, thank you so much everyone for your contributions -- I've added a note to the README, @lapseofreason, I trust this is sufficient attribution?

**Comment by lapseofreason** [comment]
@mossblaser Thanks for merging it! The mention is more than enough, it would not have been necessary, but thanks!

**Pull request merged**
